services:
  postgres:
    image: postgres:17
    container_name: nest_postgres
    environment:
      POSTGRES_DB: nest_tutorial_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"